name: Comment on Workflow Run

on:
  workflow_run:
    workflows:
      - "Test"
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - name: on artifact
        id: artifact
        uses: marocchino/on_artifact@v1
        with:
          name: all
      - uses: ./
        with:
          header: All
          number: ${{ steps.artifact.outputs.number }}
          message: |
            <details open>
            <summary>output of yarn all</summary>

            ```
            ${{ steps.artifact.outputs.all_result }}
            ```
            </details>
      - uses: ./
        with:
          header: All
          number: ${{ steps.artifact.outputs.number }}
          append: true
          hide_details: true
          message: |
            The build is over.
