name: Test
on:
  pull_request_target:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - run: |
          set -o pipefail
          mkdir -p ./pr
          echo ${{ github.event.number }} | tee ./pr/number
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "all_result<<$EOF" >> "$GITHUB_ENV"
          yarn all >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"
        id: all
      - uses: ./
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          header: All
          GITHUB_TOKEN: ${{ secrets.PAT }}
          message: |
            <details open>
            <summary>output of yarn all</summary>

            ```
            ${{ env.all_result }}
            ```
            </details>
      - uses: ./
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          header: All
          GITHUB_TOKEN: ${{ secrets.PAT }}
          append: true
          hide_details: true
          message: |
            The build is over.
